# Generated by Django 5.2 on 2025-05-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=models.CharField(blank=True, default="", max_length=255),
                max_length=255,
                unique=True,
            ),
        ),
    ]
