# Generated by Django 5.2 on 2025-05-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_followrequest_delete_friendshiprequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friends_count",
            field=models.IntegerField(default=0),
        ),
    ]
