# Generated by Django 5.2 on 2025-05-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_user_friends_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=models.EmailField(max_length=254, unique=True),
                max_length=255,
                unique=True,
            ),
        ),
    ]
