# Generated by Django 5.2 on 2025-06-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="posts_count",
            field=models.IntegerField(default=0),
        ),
    ]
