# Generated by Django 5.2 on 2025-06-22 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_user_posts_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="peoples",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
