# Generated by Django 5.2 on 2025-06-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_user_peoples"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="peoples",
            new_name="people",
        ),
    ]
