# Generated by Django 5.2 on 2025-06-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_alter_comment_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trends",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("accurences", models.IntegerField()),
            ],
        ),
    ]
