# Generated by Django 5.2 on 2025-06-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_trends"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
