# Generated by Django 5.2 on 2025-06-24 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_post_is_private"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reported_by_people",
            field=models.ManyToManyField(
                related_name="reported_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
