# Generated by Django 5.2 on 2025-06-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_alter_notification_type_of_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type_of_notification",
            field=models.CharField(
                choices=[
                    ("acceptedfollowrequest", "Accepted followrequest"),
                    ("newfollowrequest", "New followrequest"),
                    ("rejectedfollowrequest", "Rejected followrequest"),
                    ("postcomment", "Post comment"),
                    ("postlike", "Post like"),
                ],
                max_length=50,
            ),
        ),
    ]
