# Generated by Django 5.2 on 2025-07-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notification_type_of_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('newfollowrequest', 'New followrequest'), ('postcomment', 'Post comment'), ('acceptedfollowrequest', 'Accepted followrequest'), ('rejectedfollowrequest', 'Rejected followrequest'), ('postlike', 'Post like')], max_length=50),
        ),
    ]
