# Generated by Django 5.2 on 2025-07-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_alter_notification_type_of_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('postlike', 'Post like'), ('postcomment', 'Post comment'), ('rejectedfollowrequest', 'Rejected followrequest'), ('newfollowrequest', 'New followrequest'), ('acceptedfollowrequest', 'Accepted followrequest')], max_length=50),
        ),
    ]
