# Generated by Django 5.2 on 2025-08-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_alter_notification_type_of_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('postcomment', 'Post comment'), ('postlike', 'Post like'), ('newfollowrequest', 'New followrequest'), ('rejectedfollowrequest', 'Rejected followrequest'), ('acceptedfollowrequest', 'Accepted followrequest')], max_length=50),
        ),
    ]
