# Generated by Django 5.2 on 2025-09-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_alter_notification_type_of_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('acceptedfollowrequest', 'Accepted followrequest'), ('postcomment', 'Post comment'), ('rejectedfollowrequest', 'Rejected followrequest'), ('newfollowrequest', 'New followrequest'), ('postlike', 'Post like')], max_length=50),
        ),
    ]
