# Generated by Django 5.2 on 2025-10-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0014_alter_notification_type_of_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('rejectedfollowrequest', 'Rejected followrequest'), ('acceptedfollowrequest', 'Accepted followrequest'), ('newfollowrequest', 'New followrequest'), ('postlike', 'Post like'), ('postcomment', 'Post comment')], max_length=50),
        ),
    ]
